### ISSUE TITLE
User access issue - cannot remove roles or users from sites

### ISSUE THREAD

**Issue by acoleman** [unlcms/project-herbie#724]
Once you've added a user with roles to a site, you cannot remove all roles from that person (aka remove them entirely from the site). Need to be able to remove access on sites.

**Comment by sarongebre** [comment]
It seems like this issue is related to the Administer users by role module. You can find more information on the module's issue page: [Administer users by role issues](https://www.drupal.org/project/issues/administerusersbyrole?status=All&categories=All).

There is a specific [patch](https://www.drupal.org/project/administerusersbyrole/issues/3343114) that addresses this problem. However, updating the module from version 3.3 to 3.4 also appears to fix the issue.
